
import java.awt.print.PrinterException;
import java.util.Date;
import java.text.SimpleDateFormat;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author FH
 */
public class NewJFrame extends javax.swing.JFrame {
    private Date date = new Date();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jd.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("微軟正黑體", 0, 22)); // NOI18N

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 1, 22)); // NOI18N
        jLabel1.setText("生日 ：");

        show.setFont(new java.awt.Font("微軟正黑體", 1, 22)); // NOI18N

        jButton1.setFont(new java.awt.Font("微軟正黑體", 1, 22)); // NOI18N
        jButton1.setText("確定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("微軟正黑體", 1, 22)); // NOI18N
        jButton2.setText("清除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        area.setLineWrap(true);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton3.setFont(new java.awt.Font("微軟正黑體", 1, 22)); // NOI18N
        jButton3.setText("列印");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Date d = jd.getDate();
            SimpleDateFormat sf = new SimpleDateFormat("M:dd");
            String s = sf.format(d);
            String[] s2 = s.split(":");
            String mon = s2[0];
            String day = s2[1];
            show.setText("生日：" + s2[0] + "月" + s2[1] + "號");

            int birth = Integer.parseInt(mon + day);
            if (birth >= 121 && birth <= 219) {
                area.setText("水瓶座：水瓶座的人愛自由，穿著明顯比較特異，但是看起來又很舒服。有時候覺得他們不食人間煙火，有時候又覺得他們傻的可愛。一般會有一張很性感的嘴唇，挑花運很強。");
            }
            if (birth >= 220 && birth <= 320) {
                area.setText("雙魚座個性包容力強，富有直覺，悲天憫人，容易與人相處，但有時為求凡事融洽，作事缺乏原則，容易受騙上當，甚至有時會有自我催眠或自我欺騙的負面傾向。");
            }
            if (birth >= 321 && birth <= 420) {
                area.setText("白羊座熱情且鋼硬，個性強且男性化易衝動，富正義感，善良，精力充沛樂於嘗試冒險性，開創性的事物有自以為是的個性是12星座中，除了雙魚座外，其它星座都無法模仿的星座。");
            }
            if (birth >= 421 && birth <= 521) {
                area.setText("金牛座頑固，但自己不會查覺沉著，個性洗鍊，意志堅定，慎重溫和很少動，很少說，大都靜靜地當聽眾或觀察別人腦筋計算很快，但下一步卻很慢提袋也是他欣賞的。");
            }
            if (birth >= 522 && birth <= 621) {
                area.setText("雙子座具有雙重個性，如快樂或憂傷，熱情或溫柔很令人迷惑的個性，聰明，機智也善變講話速度快，且經常轉換話題不守時有偽裝自己動機的想法和慾望愛自由，不受拘束藝術天分高。");
            }
            if (birth >= 622 && birth <= 723) {
                area.setText("巨蟹座愛家，念舊不容許他人侵入自己的地盤內向，常把心事放在心底心情像月亮，常變化圓臉，五官突出。");
            }
            if (birth >= 724 && birth <= 823) {
                area.setText("獅子座討厭黑暗和無聊果斷力，自尊心強，會隱藏不如意的事，但卻表現的很堅強喜歡被稱讚有大男人的傾向有自傲的氣息");
            }
            if (birth >= 824 && birth <= 923) {
                area.setText("處女座心思細膩，敏感略帶神經質喜歡保有慣用的東西具正義感，容易批評別人缺點完美主義者，要求自己和別人一樣完美。");
            }
            if (birth >= 924 && birth <= 1023) {
                area.setText("天秤座表面很聰明，但卻時常受騙有時優雅迷人，但有時固執受爭論當他作決定時，不要打擾他;等他作好決定後，很難改變他善於言詞追求精緻生活。");
            }
            if (birth >= 1024 && birth <= 1122) {
                area.setText("天蠍座有自信，能完全的擁有自我很少說奉承的話，一旦讚美卻是真心的是一個熱情的人，也是一個無情的危險份子是一個真正憂鬱的人有英雄氣慨，會保護弱者。");
            }
            if (birth >= 1123 && birth <= 1221) {
                area.setText("射手座個性開朗，樂觀思考路線是直的，常常得罪別人而不知道，不大會說謊非常愛笑，且音量很大冒險性大，領悟性高，幽默好動腦筋常思考，且會有驚人之舉。");
            }
            
            if (birth >= 1222 || birth <= 120) {
                area.setText("摩羯座是一個有計畫的人，在一定的時間內能完成預定的目標較不憑感覺做事，而是實際去力行喜歡社會地位脾氣較古怪，對事情執著，少受左右，喜歡一個人做事。");
            }
        }  
        catch(NullPointerException e){
            area.setText("請輸入生日!!!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        area.setText("");
        show.setText("");
        jd.setDate(date);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            area.print();
            area.append("\n列印日期 : " + date);
        } catch (PrinterException e) {
            System.out.println("檔案列印失敗");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
